name: afntest
favicon: null
layout_spectrum: 0.7963216344360262
typography_spectrum: 0.6233503613620996
title: AFN Test
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#405952'
    - '#9C9B7A'
    - '#FFD393'
    - '#FF974F'
    - '#F54F29'
  brandStrength: 0.07843391667120159
  lightness: 0.30390472314320505
  saturation: 0.23117170808836818
  rhythmicContrast: 0.090507831890136
purpose: []
