name: afntest
favicon: null
layout_spectrum: 0.7671319749206305
typography_spectrum: 0.6687381227966398
title: AFN Test
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.9480459056794643
  lightness: 0.7912379100453109
  saturation: 0.39638321101665497
  rhythmicContrast: 0.2278317646123469
purpose: []
