name: afntest
favicon: null
layout_spectrum: 0
typography_spectrum: 0.6687381227966398
title: AFN Test
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0e252b'
    - '#c7b6a2'
    - '#c3a17c'
    - '#4c4744'
    - '#8c6754'
  brandStrength: 0.75
  lightness: 0
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
