typography_spectrum: 0.6233503613620996
color:
  brandColors:
    - '#405952'
    - '#9C9B7A'
    - '#FFD393'
    - '#FF974F'
    - '#F54F29'
  brandStrength: 0.07843391667120159
  lightness: 0.30390472314320505
  saturation: 0.23117170808836818
  rhythmicContrast: 0.090507831890136
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.7963216344360262
analytics:
  google: null
  facebook: null
  twitter: null
name: afntest
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - id: 5a7298cd-7d04-477f-a2f5-dbf158a4d3c9
    url: 2015-12-16-about.html
    name: ABOUT PAGE
    type: content
  - id: 044222f6-5539-4263-9a39-277a9e63ca11
    url: 2015-12-14-getting-started-on-the-grid.html
    name: Getting Started on The Grid
    type: content
favicon: null
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
title: AFN Test
purpose: []
