layout_spectrum: 0.21244140877388418
typography_spectrum: 0.17944220453500748
color:
  brandColors:
    - '#FCFFF5'
    - '#D1DBBD'
    - '#91AA9D'
    - '#3E606F'
    - '#193441'
  brandStrength: 0.14710036013275385
  lightness: 0.16729030734859407
  saturation: 0.13681170530617237
  rhythmicContrast: 0.7357857474125922
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: null
  facebook: null
  twitter: null
name: afntest
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - id: 5a7298cd-7d04-477f-a2f5-dbf158a4d3c9
    name: ABOUT PAGE
    type: content
  - id: 044222f6-5539-4263-9a39-277a9e63ca11
    name: Getting Started on The Grid
    type: content
  - id: 816d7eab-b79b-4e11-bafa-90f072a5ebf0
    name: My Photos
    type: content
favicon: null
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
title: AFN Test
purpose: []
